version: '3.7'

services:
  swarm-cd:
    image: ghcr.io/m-adawi/swarm-cd:v0.0.1
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./repos.yaml:/app/repos.yaml:ro
      - ./stacks.yaml:/app/stacks.yaml:ro